# Generated by Django 4.2 on 2023-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(max_length=200)),
                ('message_to', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
