# Generated by Django 4.2 on 2023-06-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_inquiry_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
