# Generated by Django 4.2 on 2023-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_to',
            field=models.IntegerField(),
        ),
    ]
